version: '3.1'

services:

  mariadb: 
    image: mariadb
    restart: always
    container_name: mariadb

    environment:
      MYSQL_ROOT_PASSWORD: M1nhaS&nha!

    ports:
      - "3306:3306"
    networks:
      - desafio    

networks:
  desafio:
    driver: bridge
  #   networks:
  # desafio:
  #   driver: bridge