image: microsoft/dotnet:2.2

stages:
    - build
    - test
    
variables:
    test: "AspNetCore.Test"
    
before_script:
    # - "cd src"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"